### PR TITLE
Add Laravel 8 support

### PR DESCRIPTION
**Pull request by jeffreyvr**
I have tested the package within the latest Laravel version (8.16.0) and found no issues.

I've updated Laravel version requirement to include Laravel 8^. This is also updated in the readme.

### CODE REVIEW

**Comment by Hembi** [comment]
Please accept this PR.

**Comment by anderblackhawk** [comment]
Hello! This **_PR_** gives compatibility to Laravel 8, it is so important and useful. Please accept it.

**Comment by tripex** [comment]
Can you please accept til PR??

**Comment by ahsankhatri** [comment]
I apologize for the delay due to personal issues. Merged. Closed

**Comment by jeffreyvr** [comment]
Thanks @ahsankhatri, no need to apologise, wishing you well!

**Pull request merged**
